name: TheWildEscape
version: 1.0
main: teamdjg.wildescape.main.Main
commands:
    TWE:
        description: main command
        usage: /<command> help
    bordersetup:
        description: setup the worldborder variables.
        usage: /<command> [border minimum(number)] [border maximum(number)] [border distance per night(number)] [border speed per night(number)]
        aliases: [bordersetup, bsetup, bse]
    bordercenter:
        description: place the center of the border on the place where you stand when activating the commmand.
        usage: /<command>
        aliases: [bordercenter, bcenter, bc]
    borderstart:
        description: Starts the game of wild escape. 
        usage: /<command> <tp the command sender>
        aliases: [borderstart, bstart, bst]
    borderstop:
        description: Resets en stops the wild escape game.
        usage: /<command>
        aliases: [borderstop, bstop]
    borderpauze:
        description: Pauzes the border from moving.
        usage: /<command>
        aliases: [borderpauze, bpauze, bp]
    borderresume:
        description: Resumes the border from moving.
        usage: /<command>
        aliases: [borderresume, bresume, br]        